home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [

    #example - path( 'link/', views.view_name, name='view_name')
    #/home/
    path('',views.homepage, name='homepage'),
    #/home/1
    path('img.png/', views.img,name='img'),
    path('resume/', views.pdf_view,name='resume'),
    path('blog/', views.blogpage,name='blog'),
    path('recognize/', views.recognize,name='rec'),
    path('blog/<slug:blog_id>', views.blogdetail,name='blogdetail'),
    path('graphplotter_v1/', views.graphplotter,name='gplot'),
    path('graphplotter_v2/', views.graphplotterv2,name='gplot2'),
    path('table_download/', views.table_download,name='xlsx'),
]

sabasiddiqi/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # example - path('link/',include('appname.urls'))
    # add include from django.urls
    # path('link/', views.link_view_name),

    path('admin/', admin.site.urls),
    path('', views.main_page , name='mainpage'),
    path('home/', include('home.urls',namespace='home')),
    path('tinymce/', include('tinymce.urls')),

]


#https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
import datetime


from django_mysql.models import ListCharField
# comments
# Create your models here.
# class model_name(models.Model):
#   text=models.Charfield(max_length=25)

# After updating model update database
#   python manage.py makemigrations app_name
# open shell
#   python manage.py shell
#   model_name=Model_name(model_variable=".....")
#   model_name.save()
#   Model_name.objects.all()

class CatIndex(MPTTModel):
    name = models.CharField(max_length=100, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    link = models.CharField(max_length=500, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        template = '{0.name}'
        return template.format(self)



class GraphInput(models.Model):
    x = models.FloatField()
    y = models.FloatField()

    #def __str__(self):
        #template = '{0.x} {0.y}'
        #return template.format(self)
        #return self.x
    #   return '%d %d' % (self.x, self.y)

from django.db import models
from tinymce import HTMLField

class Post(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=250,null=True)
    content = HTMLField('Content')
    draft = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

home/forms.py
from django import forms
from .models import GraphInput


class GraphInputForm(forms.ModelForm):
    class Meta:
        model = GraphInput
        fields = ['x','y']
        widgets = {
            'x': forms.TextInput(attrs={'type': 'number','id':'form_homework','min': '-1000.00','max':'1000.00','step':'0.01'}),
            'y': forms.TextInput(attrs={'type': 'number','id':'form_homework','min': '-1000.00','max':'1000.00','step':'0.01'})
        }

from django import forms
from tinymce import TinyMCE
from .models import Post


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = '__all__'

home/views.py
from django.shortcuts import render, render_to_response
from .models import GraphInput, CatIndex, Post
from .forms import GraphInputForm
from django.shortcuts import redirect
from django.http import FileResponse, Http404, HttpResponse
import os
from sabasiddiqi.settings import MEDIA_ROOT
import io
import matplotlib.pyplot as plt
import xlsxwriter
from PIL import Image
import re
import base64
import numpy as np

def main_page(request):
    return redirect('home:homepage')

def homepage(request):
    context={'index': CatIndex.objects.all(), 'blog': Post.objects.all()}
    return render(request, 'home/home.html', context)

def blogpage(request):
    context={'blog': Post.objects.all()}
    return render(request, 'home/blog.html', context)

def recognize(request):

    #https://www.reddit.com/r/learnpython/comments/6lqsrp/converting_a_dataurl_to_numpy_array/
    if request.method == 'POST':
        # in your view function
        image_data = request.POST.get('image_data',False)
        imgstr = re.search(r'base64,(.*)', image_data).group(1)
        #print(imgstr)

        ### To save the file
        dir_name = "media/"
        base_filename = "output"
        suffix = ".png"
        if not os.path.exists(dir_name):
            os.makedirs(dir_name)
        filename=os.path.join(dir_name, base_filename + suffix)
        print("filename is",filename)


        with open(filename,'wb') as f:
            f.write(base64.b64decode(imgstr))


        ### to save is directly as numpy array
        size = 28, 28
        image_bytes = io.BytesIO(base64.b64decode(imgstr))
        im = Image.open(image_bytes)
        im.thumbnail(size
                     #, Image.ANTIALIAS
                     #,Image.BILINEAR
                     )
        arr = np.array(im)[:,:,0]
        arr=arr.ravel()
        im.show()

        import pickle
        scale = pickle.load(open('media/ml/scale.sav', 'rb'))
        pca = pickle.load(open('media/ml/pca.sav', 'rb'))
        model = pickle.load(open('media/ml/model.sav', 'rb'))
        arr=np.where(arr>0, 1, 0)
        test_data=[arr]
        #print(arr)
        X_std_test = scale.transform(test_data)
        print(X_std_test.size)
        test_pca_b = pca.transform(X_std_test)
        print(test_pca_b.size)
        result=model.predict(test_pca_b)
        print(result)


        #print(arr)
        #print(arr.sum())
        #print(im.size)
        #print(arr.size)

    context=None;
    return render(request, 'home/recognize.html', context)

def blogdetail(request,blog_id):

    blog_id=blog_id.replace('-',' ')
    blog_detail=Post.objects.filter(title__iexact=blog_id).all()
    context={'blog_detail': blog_detail}
    #return HttpResponse("It is" + str(detail) + str(blog_id))
    return render(request, 'home/blogdetail.html', context)



def graphplotterv2(request):

    if request.method == 'POST' and 'add' in request.POST:
        form = GraphInputForm(request.POST)
        if form.is_valid():
            form.save()


    #when the page refreshes
    if request.method == 'GET':
        GraphInput.objects.all().delete()
        request.session['color_sel'] = 'red'
        request.session['plot_type'] = 'line'
        request.session['title'] = 'Graph'
        request.session['xlabel'] = 'x-axis'
        request.session['ylabel'] = 'y-axis'

    if request.method == 'POST' and 'colors' in request.POST:
        print('Color Selected')
        request.session['color_sel'] = request.POST['colors']

    if request.method == 'POST' and 'labels' in request.POST:
        if request.POST['title']:   request.session['title'] = request.POST['title']
        if request.POST['xlabel']:  request.session['xlabel'] = request.POST['xlabel']
        if request.POST['ylabel']:  request.session['ylabel'] = request.POST['ylabel']

    if request.method == 'POST' and 'types' in request.POST:
        print('Line Selected')
        request.session['plot_type'] = request.POST['types']

    form = GraphInputForm()

    data = GraphInput.objects.all()
    template = 'home/plot2.html'
    context = {'form': form, 'data': data}
    return render(request, template, context)

def graphplotter(request):

    if request.method == 'POST' and 'add' in request.POST:
        form = GraphInputForm(request.POST)
        print('Add Data')
        if form.is_valid():
            print('Form is valid')
            form.save()

    if request.method == 'GET':
        GraphInput.objects.all().delete()
        request.session['color_sel'] = 'red'
        request.session['plot_type'] = 'line'
        print('Clear Data')

    if request.method == 'POST' and 'colors' in request.POST:
        print('Color Selected')
        request.session['color_sel'] = request.POST['colors']

    if request.method == 'POST' and 'types' in request.POST:
        print('Line Selected')
        request.session['plot_type'] = request.POST['types']


    form = GraphInputForm()

    data = GraphInput.objects.all()
    template = 'home/plot.html'
    context = {'form': form, 'data': data}
    return render(request, template, context)

def img(request):
    color_sel = request.session['color_sel']
    plot_type = request.session['plot_type']
    title_name = request.session['title']
    x_label = request.session['xlabel']
    y_label = request.session['ylabel']
    data_x=[]
    data_y=[]
    for key in GraphInput.objects.all():
        data_x.append(key.x)
        data_y.append(key.y)
    plt.Figure()
    x = data_x
    y = data_y
    if plot_type=='line':
        plt.plot(x, y, color=color_sel)
    elif plot_type=='scatter':
        plt.scatter(x, y, color=color_sel)
    else:
        plt.plot(x, y, color=color_sel)
    plt.title(title_name)
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    plt.close('all')
    response = HttpResponse(buf.getvalue(), content_type='image/png')
    return response

def pdf_view(request):
    try:
        dir_name=MEDIA_ROOT
        base_filename='sabasiddiqi_resume'
        suffix = '.pdf'
        resume_path=os.path.join(dir_name, base_filename + suffix)
        return FileResponse(open(resume_path,'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()
    #C:\Users\sabas\Workspace\sabasiddiqi\sabasiddiqi\media\sabasiddiqi_resume.pdf

#https://stackoverflow.com/questions/39394861/read-django-data-from-model-and-write-it-using-xlsxwriter
def table_download(request):
    # Create a workbook and add a worksheet.
    output = io.BytesIO()
    workbook = xlsxwriter.Workbook(output, {'in_memory': True})
    worksheet = workbook.add_worksheet('Reporte3a5')
    bold = workbook.add_format({'bold': True})
    # Some data we want to write to the worksheet.
    reporte = GraphInput.objects.all() #my model

    # Start from the first cell. Rows and columns are zero indexed.
    row = 1
    col = 0

    # Iterate over the data and write it out row by row.
    for linea in reporte:
        worksheet.write(row, col, linea.x)
        worksheet.write(row, col + 1, linea.y)
        #worksheet.write(row, col + 2, linea.ship_set)
        row += 1

    # Write the title for every column in bold
    worksheet.write('A1','X-Coordinate', bold)
    worksheet.write('B1', 'Y-Coordinate', bold)

    workbook.close()

    output.seek(0)
    response = HttpResponse(output.read(), content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    response['Content-Disposition'] = "attachment; filename=Reporte3a5.xlsx"

    return response

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>    {% block title %} {% endblock %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body style="background-color:rgba(0, 51, 51,1);">

<!-- Navigation Bar Horizontal -->
<nav class="navbar navbar-inverse navbar-expand-sm">

  <div class="container-fluid">

    <!-- Nav Header -->
    <div class="navbar-header">
      <a style="font: italic bold 20px Georgia, serif; color:white; margin-right:30px;"
         class="navbar-brand" href="{% url 'mainpage' %}">Saba Siddiqi</a>
    </div>

    <!-- NAv Oprtions -->
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'home:homepage' %}">Home</a></li>
      <li class="inactive"><a href="{% url 'home:blog' %}">Blog</a></li>
      <li class="inactive"><a href="{% url 'home:gplot2' %}">GraphPlotter</a></li>
    </ul>

    <!-- Right Media Links -->
    <ul class="nav navbar-nav navbar-right">
      <li><a target="_blank" href="{% url 'home:resume' %}">Resume</a></li>
      <li><a target="_blank" href="https://github.com/SabaSiddiqi"><span class="fab fa-github fa-lg"></span> Github </a></li>
      <li><a target="_blank" href="https://www.linkedin.com/in/saba-siddiqi-77428071/"><span class="fab fa-linkedin fa-lg"></span> LinkdIn </a></li>
      <li><a target="_blank" href="https://www.kaggle.com/sabasiddiqi/"><span class="fab fa-kaggle fa-lg"></span> Kaggle </a></li>
    </ul>

  </div>


</nav>

<div>
    {% block content %}
    {% endblock %}
</div>



</body>


</html>

home/templates/home/blog.html
{% extends 'home/base.html' %}

{% block title %}
Saba Siddiqi
{% endblock %}




{% block content %}

<style>

/* Add a card effect for articles */
.card {
   display:block;
   padding: 10px 10px 10px 10px;
   margin:10px;
   height:300px;
   white-space: normal;

}

.a{
  overflow: hidden;
  display: inline-block;
  max-width:100%;
  height:130px;


}




</style>

<div class="container" >

    <h1 style="color:white;">Saba's Blog</h1><br>

    <div class="row">

        {% for each_model in blog %}
        {% if not each_model.draft %}

        <ul class="list-group col-md-4">
            <li class="list-group-item disabled">
                <h4><a href="{% url 'home:blogdetail' each_model.title|slugify %}"><b>{{each_model.title}}</b></a></h4>
            </li>
            <li class="list-group-item">
                <div class="card">
                    <h5><em>{{each_model.description}}</em></h5>
                    <div class="a">{{each_model.content|safe}}</div>
                    <hr>
                    <p style="float:right;">Updated at: <b>{{each_model.updated_at}}</b></p>
                </div>
            </li>
                </ul>
            </li>
        </ul>

                    {% endif %}
        {% endfor %}



    </div>




</div>


{% endblock %}

home/templates/home/blogdetail.html
{% extends 'home/base.html' %}

{% block title %}
Saba Siddiqi
{% endblock %}

{% block content %}

<style>

/* Add a card effect for articles */
.card {
   padding: 20px;
   margin-top: 20px;
   word-wrap: break-word;
   margin:10px;
}

</style>

<div class="container" >

    <h1 style="color:silver;">Saba's Blog</h1><br>

        {% for each_model in blog_detail %}
        {% if not each_model.draft %}

        <ul class="list-group">
            <li class="list-group-item disabled">
                <b><h2 style="margin-left:40px;">{{each_model.title}}</h2></b>
                <h5 style="float:right;">Updated at : <b>{{each_model.updated_at}}</b></h5><br>
            </li>
            <li class="list-group-item">
                <div class="card">
                    <h5><em>{{each_model.description|safe}}</em></h5><br>
                    <div class="a">{{each_model.content|safe}}</div>
                    <hr>
                    <p style="float:right;">Created at: <b>{{each_model.created_at}}</b></p>
                </div>
            </li>
                </ul>
            </li>
        </ul>

        {% endif %}
        {% endfor %}


</div>


{% endblock %}

home/templates/home/forms.html
{% extends 'home/base.html' %}

{% block content %}

<form method="post">
    <div>
        {% csrf_token %}
        {{form.x}}
    {{form.y}}
    <button type="submit" name="add">Add</button>
    </div>
</form>
<form method="post" >
    {% csrf_token %}
    <button type="submit" name="clear">Clear</button>
</form>

<div class="container">{% csrf_token %}
  <h2>Bordered Table</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>X-Coordinate</th>
        <th>Y-Coordinate</th>
      </tr>
    </thead>
    <tbody>

    {% for value in data %}
    <tr>
        <td>{{value.x}}</td>
        <td>{{value.y}}</td>
    </tr>
    {% endfor %}

    </tbody>
  </table>
</div>

<form method="post" >
    {% csrf_token %}
    <input type="submit" value="Select" name="col">
</form>

<img src="/home/img.png/">

{% endblock %}

{% block image %}

{% endblock %}

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block title %}
Saba Siddiqi
{% endblock %}

{% block content %}


<style>
/* unvisited link */
a:link {
  color: white;
}

/* visited link */
a:visited {
  color: white;
}

/* mouse over link */
a:hover {
  color: black;
}

/* selected link */
a:active {
  color: white;
}

.j{
margin-top:10px;
background-color:rgba(0, 51, 51,0.7);
color:white;}



</style>


<div class="container">

<div class="row">

    <div class="col-md-8">
        <ul class="list-group">
        {% load mptt_tags %}
        {% recursetree index %}
            <li class="list-group-item disabled" style=""  >
                <h4><b>{{ node.name }}</b></h4></li>
            {% if not node.is_leaf_node %}
                {% for i in node.children.all %}
                    <li class="list-group-item" style="background-color:#141f1f;">
                        <h4 style="color:white;"  >
                            <a href={{i.link}}>{{i.name}}</a>
                            </h4>
                    {% if not i.is_leaf_node %}
                         <ul class="list-group "  >
                        {% for j in i.children.all %}
                            <li class="list-group-item j">
                                 <a style="padding-left:10px;" target="_blank" href={{j.link}}>{{j}}</a>
                            </li>
                        {% endfor %}
                         </ul>
                    {% endif %}
                {% endfor %}
            </li>
            {% endif %}
        </li>
    {% endrecursetree %}
        </ul>





    </div>

    <div class="col-md-4">

        <ul class="list-group">
        <li class="list-group-item disabled"><h4>About Me</h4></li>
            <li class="list-group-item">
                   Hello, I am Saba.
                       I am a Machine Learning Enthusiast,
                       with a background in Electrical and Computer Engineering.
                      I spent most of my time solving Machine Learning Problems.
                       And I love to paint.

                    <br><h5 align="left"><b>- Learning, to make a difference.</b></h5></h4>


            </li>
        </li>
        </ul>

        <ul class="list-group">
        <li class="list-group-item disabled"><h4>It's Never too Late</h4></li>
                       <li class="list-group-item">
                           <h4>
                           <q><i>All our dreams can come true,
                               if we have the courage to pursue them.</i></q>
                               <br><h5 align="right">– Walt Disney</h5></h4>
                       </li>
            </li>
        </ul>

        <ul class="list-group">
        <li class="list-group-item disabled"><h4>Recent Blogs</h4></li>
               <li class="list-group-item">
                    <div >
                    {% for each_model in blog %}
                        {% if not each_model.draft %}
                        <h5 style="margin-left:10px;">
                            <a href="{% url 'home:blogdetail' each_model.title|slugify %}" style="color:black;">
                                {{each_model.title}}
                            </a>
                        </h5>
                        {% endif %}
                    {% endfor %}
                    </div>

               </li>
                </ul>
            </li>
        </ul>


    </div>




</div>

</div>






{% endblock %}

home/templates/home/plot.html
{% extends 'home/base.html' %}
{% block title %} Graph Plotter {% endblock %}
{% block content %}

<div class="container" >

    <div class="row">
        <div class="col-md-6" name="left-side">

            <div class="row">

                <div class="col-md-8 b-set">

                    <form method="post">{% csrf_token %}
                    <div class="col-md-6">
                        Enter X-Coordinate:  {{form.x}}
                        <br>
                        Enter Y-Coordinate:  {{form.y}}
                    </div>
                    <div class="col-md-6">
                        <br>
                        <button type="submit" name="add" class="btn btn-primary">Add Values</button>
                    </div>
                     </form >
                    <form method="get">{% csrf_token %}
                    <button type="submit" name="clear" style="margin-left:3%;margin-top:2%;" class="btn btn-primary">Clear Graph</button>
                    </form>

                </div>

                <div class="col-md-4 b-set">

                    <form method = "post" action = ".">{% csrf_token %}
                    <h5> Plot Options </h5><br>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-dark btn-block dropdown-toggle" data-toggle="dropdown"> Color <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><button  type = "submit"  name="colors" value="black" class="btn btn-link"> Black </button></li>
                            <li><button  type = "submit"  name="colors" value="blue" class="btn btn-link"> Blue </button></li>
                            <li><button  type = "submit"  name="colors" value="red" class="btn btn-link"> Red </button></li>
                            <li><button  type = "submit"  name="colors" value="green" class="btn btn-link"> Green </button></li>
                            <li><button  type = "submit"  name="colors" value="cyan" class="btn btn-link"> Cyan </button></li>
                            <li><button  type = "submit"  name="colors" value="magenta" class="btn btn-link"> Magenta </button></li>
                            <li><button  type = "submit"  name="colors" value="Yellow" class="btn btn-link"> Yellow </button></li>
                        </ul>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-block dropdown-toggle" data-toggle="dropdown"> Type <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><button  type = "submit"  name="types" value="line" class="btn btn-link"> Line </button></li>
                            <li><button  type = "submit"  name="types" value="scatter" class="btn btn-link"> Scatter </button></li>
                        </ul>
                    </div>
                    </form>

                </div>

            </div>

            <h3>Graph Data</h3>

            <div class="row table-wrapper-scroll-y" name="data-table">
                {% csrf_token %}
                    <table class="table table-bordered ">
                        <thead>
                            <tr>
                                <th class="">X-Coordinate</th>
                                <th class="">Y-Coordinate</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for value in data %}
                            <tr>
                                <td class="">{{value.x}}</td>
                                <td class="">{{value.y}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>

        </div>


        <div class="col-md-6">
            <img src="/home/img.png/">
        </div>

    </div>

</div>

{% endblock %}

home/templates/home/plot2.html
{% extends 'home/base.html' %}
{% block title %} Graph Plotter{% endblock %}
{% block content %}

<div class="container-fluid" style="background-color:white; border: 50px solid white;">

    <div class="row">

        <!-- Graph Info -->
        <div class="col-md-6" name="left-side">

            <div class="row">

                <!-- Enter Data -->
                <div class="col-md-8 b-set">

                    <form method="post">{% csrf_token %}
                    <div class="col-md-6">
                        Enter X-Coordinate:  {{form.x}}
                        <br>
                        Enter Y-Coordinate:  {{form.y}}
                    </div>
                    <div class="col-md-6">
                        <br>
                        <button type="submit" name="add" class="btn btn-primary">Add Values</button>
                    </div>
                     </form >
                    <form method="get">
                        <button type="submit" name="clear" style="margin-left:3%;margin-top:2%;" class="btn btn-primary">
                            Clear Graph
                        </button>
                    </form>

                </div>

                <!-- Graph Options -->
                <div class="col-md-4 b-set">

                    <form method = "post" action = ".">{% csrf_token %}
                    <h5> Plot Options </h5><br>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-dark btn-block dropdown-toggle" data-toggle="dropdown"> Color <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><button  type = "submit"  name="colors" value="black" class="btn btn-link"> Black </button></li>
                            <li><button  type = "submit"  name="colors" value="blue" class="btn btn-link"> Blue </button></li>
                            <li><button  type = "submit"  name="colors" value="red" class="btn btn-link"> Red </button></li>
                            <li><button  type = "submit"  name="colors" value="green" class="btn btn-link"> Green </button></li>
                            <li><button  type = "submit"  name="colors" value="cyan" class="btn btn-link"> Cyan </button></li>
                            <li><button  type = "submit"  name="colors" value="magenta" class="btn btn-link"> Magenta </button></li>
                            <li><button  type = "submit"  name="colors" value="Yellow" class="btn btn-link"> Yellow </button></li>
                        </ul>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-block dropdown-toggle" data-toggle="dropdown"> Type <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><button  type = "submit"  name="types" value="line" class="btn btn-link"> Line </button></li>
                            <li><button  type = "submit"  name="types" value="scatter" class="btn btn-link"> Scatter </button></li>
                        </ul>
                    </div>
                    </form>

                </div>

            </div>

            <!-- Graph Labels -->
            <div class="row b-set" >
                <a data-toggle="collapse" data-target="#demo">Graph Labels:</a><br>
                <div id="demo" class="panel-collapse collapse">
                    <br>
                    <form method="post">{% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon">Title</span>
                    <input type="text" class="form-control" name="title" placeholder="Enter title here">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">X-Label</span>
                    <input type="text" class="form-control" name="xlabel" placeholder="Enter x-label here">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">Y-Label</span>
                    <input type="text" class="form-control" name="ylabel" placeholder="Enter y-label here">
                </div>
                <br>
                <button type="submit" name="labels" class="btn btn-primary">Set</button>
            </form>
                </div>
            </div>

            <!-- Graph Data and Download -->
            <h4><br>Graph Data
                <a style="float:right;" href="{%url 'home:xlsx' %}" download>
                    <span class="fas fa-download fa-md"></span>
                </a>
            </h4>
            <div class="row table-wrapper-scroll-y" name="data-table">
                {% csrf_token %}
                    <table class="table table-bordered ">
                        <thead>
                            <tr>
                                <th class="">X-Coordinate</th>
                                <th class="">Y-Coordinate</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for value in data %}
                            <tr>
                                <td class="">{{value.x}}</td>
                                <td class="">{{value.y}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>

        </div>

        <!-- Graph -->
        <div class="col-md-6">
            <img src="/home/img.png/">
            <a style="float:right;" href="/home/img.png" download><span class="fas fa-download fa-lg"></span>
            </a>
        </div>

    </div>

</div>

{% endblock %}